apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mariadb.DATABASE_SERVICE_NAME }}-node
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mariadb
  type: NodePort
  # clusterIP: None
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
      protocol: TCP
      nodePort: 30001