apiVersion: v1
kind: Service
metadata:
  name: visiativ-svc-node
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: visiativ
  type: NodePort
  # clusterIP: None
  ports:
    - name: visiativ
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 30002