apiVersion: v1
kind: Service
metadata:
  name: visiativ-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: visiativ
  type: ClusterIP
  # clusterIP: None
  ports:
    - name: visiativ
      port: 8080
      targetPort: 8080
      protocol: TCP